### ISSUE TITLE
Beispiel-Logos für das Brandlogo und Applogo hinzufügen

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components-icons-and-fonts#1]
Das neue Theme Authentic stellt im Header einen Platzhalter für die das Brandlogo und das Applogo bereit.
Diese Beispieldateien sollen allgemein zur Verfügung gestellt werden. Das Applogo ist gleichzeitig die Vorlage für das neue favicon

**Comment by thodic77** [comment]
Erfolgreich geprüft.
