### ISSUE TITLE
Icons zum Thema Barrierefreiheit hinzufügen

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components-icons-and-fonts#13]
Folgende Icons  aus der "Core Line free" der Streamline-Icons sollen ergänzt werden.

- hearing-deaf-1
- wheelchair-1
- braille-blind

ein selbsterstelltes Icon für die Gebärdensprache soll ergänzt werden.

**Comment by thodic77** [comment]
Code-Review erfolgreich durchgeführt.
